---
- hosts: spring
  become: True
  tasks:
    - name: Install docker daemon
      yum:
        name: docker
        state: present
    - name: Start and enable dokeer daemon
      service:
        name: docker
        state: started
        enabled: True
    - name: Install java
      yum:
        name: java
        state: present
    - name: Create myspring container
      docker_container:
        name: myspring
        image: bhargav7329/spring-boot-api:1.0
        ports: 80:8080
